# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.10-slim

WORKDIR /app

# Copy the project files
COPY . /app

# Upgrade pip and install project dependencies
RUN pip install --upgrade pip \
    && pip install .

# Expose port if needed. MCP communication over stdio so not required

# Command to launch the MCP server
CMD ["fewsats-mcp"]
